call pathogen#infect()
Helptags
set nocompatible
" format
set autoindent
set nu
"set smartindent
set showmatch
" set textwidth=80
set title
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
" syntax
syntax on
syntax enable
" support 256 colors in Lion terminal 
set t_Co=256
" files 
filetype on
filetype indent on
filetype plugin on
" always show file name
set modeline
set ls=2
" colorscheme
colorscheme molokai
" format with goimports instead of gofmt on save
let g:go_fmt_command = "goimports"
" enable fmt on save
let g:go_fmt_autosave = 1
" add the closing braces
inoremap {      {}<Left>
inoremap {<CR>  {<CR>}<Esc>O
inoremap {{     {
inoremap {}     {}
