FROM vallard/ruby:v1
MAINTAINER Vallard Benincosa "vallard@benincosa.com"
# Unicorn Setup
ENV PATH /usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN /bin/bash -l -c "gem install unicorn"
